# Generated by Django 4.2.2 on 2023-06-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionsHub', '0005_rename_items_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='carts', to='auctionsHub.item'),
        ),
    ]
