# Generated by Django 4.2.2 on 2023-06-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionsHub', '0006_remove_cart_item_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='auction',
        ),
        migrations.AddField(
            model_name='comment',
            name='items',
            field=models.ManyToManyField(related_name='comments', to='auctionsHub.item'),
        ),
    ]
